config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :administrators, only: [:index]  do
    get 'users'                       => 'administrators#users',                on: :collection
    get 'malls'                       => 'administrators#malls',                on: :collection
    get 'stores'                      => 'administrators#stores',               on: :collection
    get 'brands'                      => 'administrators#brands',               on: :collection
    get 'products'                    => 'administrators#products',             on: :collection
    get 'promotions'                  => 'administrators#promotions',           on: :collection
    get 'setting'                     => 'administrators#setting',              on: :collection
    get 'import'                      => 'administrators#import',               on: :collection
    # collection { post :import }
  end
  
  resources :malls, only:[:new, :edit, :create, :update] do
    collection { post :import }
  end
  
  resources :malls, only:[] do
    get   ':name/:permalink'                      => 'stores#show',       on: :collection, as: :show
    get   ':name/:permalink/:product_id'          => 'products#show',     on: :collection, as: :products_show
    post  ':name/:permalink/:product_id/reviews'  => 'reviews#create',    on: :collection, as: :reviews_create
    post  ':mall_id/follow'                       => 'malls#follow',      on: :collection, as: :follow
    post  ':mall_id/unfollow'                     => 'malls#unfollow',    on: :collection, as: :unfollow
    resources :stores, only:[:new, :edit, :create, :update]
  end

  resources :brands, only:[:new, :edit, :create, :update] do
    collection { post :import }
    post  ':brand_id/follow'      => 'brands#follow',    on: :collection, as: :follow
    post  ':brand_id/unfollow'    => 'brands#unfollow',  on: :collection, as: :unfollow
  end

  resources :stores, only:[:index] do
    collection { post :import }
    post  ':store_id/follow'      => 'stores#follow',    on: :collection, as: :follow
    post  ':store_id/unfollow'    => 'stores#unfollow',  on: :collection, as: :unfollow
  end

  resources :users, only:[] do
    post  ':user_id/follow'       => 'users#follow',    on: :collection, as: :follow
    post  ':user_id/unfollow'     => 'users#unfollow',  on: :collection, as: :unfollow
  end

  resources :products, only:[] do
    post  ':product_id/like'      => 'products#like',     on: :collection, as: :like
    post  ':product_id/dislike'   => 'products#dislike',  on: :collection, as: :dislike
  end

  resources :reviews, only:[] do
    post  ':review_id/like'      => 'reviews#like',     on: :collection, as: :like
    post  ':review_id/dislike'   => 'reviews#dislike',  on: :collection, as: :dislike
  end

  get   '/:permalink'                 => 'home#profile',                        as: "profile",              :constraints => { :name => /[^\/]+/ }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, uniqueness: true

  acts_as_followable
  acts_as_follower
  acts_as_voter

  has_one   :permalink, as: :linkable
  has_many  :reviews
  has_one   :image,       as: :imageable

  has_many :user_roles
  has_many :roles, through: :user_roles

  def is_admin
    !roles.where(name:"Admin").blank?
  end

  def add_image file
    unless file.blank?
      if image.blank?
        img           = Image.new
        img.imageable = self
      else
        img           = self.image
      end
      img.avatar      = file
      img.save
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!

  def follow
    @user = User.find_by_id params[:user_id]  
    current_user.follow(@user)
    @follower_size = @user.followers_count
    if params[:profile]
      @following_size = current_user.follow_count
      respond_to do |format|
        unless params[:following_id]
          format.js { render "user_follower" }
        else        
          format.js { render "user_following" }
        end
        format.html
      end
    else
    end
  end

  def unfollow
    @user = User.find_by_id params[:user_id] 
    current_user.stop_following(@user)
    @follower_size = @user.followers_count
    if params[:profile]
      @following_size = current_user.follow_count
      respond_to do |format|
        unless params[:following_id]
          format.js { render "user_unfollower" }
        else        
          format.js { render "user_unfollowing" }
        end
        format.html
      end
    else
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/component/_follow.html.erb
<%= link_to follow_users_path(@user), method: :post, remote:true, class: "button", id:"spot-button" do %>
  <i class="spicon spicon-plus"></i> SPOT
<% end %>

app/views/users/component/_unfollow.html.erb
<%= link_to unfollow_users_path(@user), method: :post, remote:true, class: "button", id:"spot-button" do %>
  <i class="spicon spicon-plus"></i> SPOTTING
<% end %>

app/views/users/component/_user_follower.html.erb
<%= link_to follow_users_path(follower), method: :post, remote:true, data:{params:"profile=true&follower_id=#{follower.id}&is_current_user_page=#{is_current_user_page}"}, class: "button", id:"user-follower-#{follower.id}" do %>
  <i class="spicon spicon-plus"></i> SPOT
<% end %>

app/views/users/component/_user_following.html.erb
<%= link_to follow_users_path(following), method: :post, remote:true, data:{params:"profile=true&following_id=#{following.id}&is_current_user_page=#{is_current_user_page}"}, class: "button", id:"user-following-#{following.id}" do %>
  <i class="spicon spicon-plus"></i> SPOT
<% end %>

app/views/users/component/_user_unfollower.html.erb
<%= link_to unfollow_users_path(follower), method: :post, remote:true, data:{params:"profile=true&follower_id=#{follower.id}&is_current_user_page=#{is_current_user_page}"}, class: "button", id:"user-follower-#{follower.id}" do %>
  <i class="spicon spicon-plus"></i> SPOTTING
<% end %>

app/views/users/component/_user_unfollowing.html.erb
<%= link_to unfollow_users_path(following), method: :post, remote:true, data:{params:"profile=true&following_id=#{following.id}&is_current_user_page=#{is_current_user_page}"}, class: "button", id:"user-following-#{following.id}" do %>
  <i class="spicon spicon-plus"></i> SPOTTING
<% end %>