config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :administrators, only: [:index]  do
    get 'users'                       => 'administrators#users',                on: :collection
    get 'malls'                       => 'administrators#malls',                on: :collection
    get 'stores'                      => 'administrators#stores',               on: :collection
    get 'brands'                      => 'administrators#brands',               on: :collection
    get 'products'                    => 'administrators#products',             on: :collection
    get 'promotions'                  => 'administrators#promotions',           on: :collection
    get 'setting'                     => 'administrators#setting',              on: :collection
    get 'import'                      => 'administrators#import',               on: :collection
    # collection { post :import }
  end
  
  resources :malls, only:[:new, :edit, :create, :update] do
    collection { post :import }
  end
  
  resources :malls, only:[] do
    get   ':name/:permalink'                      => 'stores#show',       on: :collection, as: :show
    get   ':name/:permalink/:product_id'          => 'products#show',     on: :collection, as: :products_show
    post  ':name/:permalink/:product_id/reviews'  => 'reviews#create',    on: :collection, as: :reviews_create
    post  ':mall_id/follow'                       => 'malls#follow',      on: :collection, as: :follow
    post  ':mall_id/unfollow'                     => 'malls#unfollow',    on: :collection, as: :unfollow
    resources :stores, only:[:new, :edit, :create, :update]
  end

  resources :brands, only:[:new, :edit, :create, :update] do
    collection { post :import }
    post  ':brand_id/follow'      => 'brands#follow',    on: :collection, as: :follow
    post  ':brand_id/unfollow'    => 'brands#unfollow',  on: :collection, as: :unfollow
  end

  resources :stores, only:[:index] do
    collection { post :import }
    post  ':store_id/follow'      => 'stores#follow',    on: :collection, as: :follow
    post  ':store_id/unfollow'    => 'stores#unfollow',  on: :collection, as: :unfollow
  end

  resources :users, only:[] do
    post  ':user_id/follow'       => 'users#follow',    on: :collection, as: :follow
    post  ':user_id/unfollow'     => 'users#unfollow',  on: :collection, as: :unfollow
  end

  resources :products, only:[] do
    post  ':product_id/like'      => 'products#like',     on: :collection, as: :like
    post  ':product_id/dislike'   => 'products#dislike',  on: :collection, as: :dislike
  end

  resources :reviews, only:[] do
    post  ':review_id/like'      => 'reviews#like',     on: :collection, as: :like
    post  ':review_id/dislike'   => 'reviews#dislike',  on: :collection, as: :dislike
  end

  get   '/:permalink'                 => 'home#profile',                        as: "profile",              :constraints => { :name => /[^\/]+/ }
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to  :brand
  belongs_to  :mall
  has_many    :reviews
  has_many    :store_product
  has_many    :products, through: :store_product

  def self.import(file, is_update)
    if is_update
      
    else
      log ||= Logger.new("#{Rails.root}/log/store_import.log")
      spreadsheet = open_spreadsheet(file)
      log.info(" Start importing for #{file.original_filename} ")
      log.info(" ----- ")
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        mall                      = Mall.find_by_name(spreadsheet.row(i)[3])
        unless mall.blank?
          store                     = self.new
          store.name                = spreadsheet.row(i)[1]                
          store.kind                = spreadsheet.row(i)[2]                
          store.mall                = mall             
          store.desc                = spreadsheet.row(i)[4]                
          store.area                = spreadsheet.row(i)[5]                
          store.city                = spreadsheet.row(i)[6]                
          store.standing_floor_name = spreadsheet.row(i)[8] 
          store.address             = mall.address             
          store.phone               = spreadsheet.row(i)[9]
          unless spreadsheet.row(i)[7].blank?
            brand       = Brand.find_by_name spreadsheet.row(i)[7]
            store.brand = brand
          end
          store.permalink           = spreadsheet.row(i)[1]
          store.to_slug
          if store.save
            log.info("#{i-1} - Store successfully saved: #{store.name}, #{store.permalink}")
          end
        end
      end
      log.info(" ----- ----- ----- ----- ")
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path)
    when ".xls" then Roo::Excel.new(file.path)
    when ".xlsx" then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}" 
    end
  end

  def to_slug counter=0
    self.permalink = self.permalink.strip
    self.permalink.gsub! /\s*@\s*/, " at "
    self.permalink.gsub! /\s*&\s*/, " dan "
    self.permalink = self.permalink.parameterize
    self.permalink.gsub! /[-_]{2,}/, "-"
    self.permalink.gsub! /-+/, "-"
    self.permalink.gsub! /\A[-\.]+|[-\.]+\z/, ""
    if self.mall.stores.exists?(:permalink => self.permalink)
      self.permalink = "#{self.permalink}-#{counter+1}"
      self.to_slug counter + 1
    end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_filter :modal_search_exist,       only:[:index, :show]

  def show
    @mall               = Mall.find_by_permalink params[:name]
    @store              = @mall.stores.find_by permalink: params[:permalink]
    @products           = @store.products 
    @is_user_following  = current_user.following?(@store)
  end

  def follow
    @store = Store.find_by_id params[:store_id]  
    current_user.follow(@store)
    if params[:profile]
      respond_to do |format|
        unless params[:following_id]
          format.js { render "user_follower" }
        else        
          format.js { render "user_following" }
        end
        format.html
      end
    else
    end
  end

  def unfollow
    @store = Store.find_by_id params[:store_id]  
    current_user.stop_following(@store)
    if params[:profile]
      @following_size = current_user.follow_count
      respond_to do |format|
        format.js { render "user_unfollow" }
        format.html
      end
    else
    end
  end

  def index
    @malls = Mall.all.includes(:stores)
  end

  def import
    Store.import(params[:file], params[:is_update])
    redirect_to import_administrators_url
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/follow.js.erb
$("#spot-button").html( "<%= escape_javascript(render 'stores/component/unfollow') %>" );

app/views/stores/index.html.erb
<!-- Canvas -->
<div class="canvas">
  <!-- Sidebars -->
  <%= render "layouts/sidebar"%>

  <!-- Content -->
  <div class="content">
    <!-- Header -->
    <%= render partial: "container/header", locals: { title: "SEARCH" }%>

    <!-- Container -->
    <div class="container">
      <!-- <div class="search-body">
        <span>Results 126 Merchants</span>
      </div> -->
      <div class="shop">
        <ul class="listing">
          <% @malls.each do |mall| %>
            <%= render partial: "list/stores", locals:{mall:mall}%>
          <% end %>
        </ul>
        <div class="loadmore">
          <a href="#loadmore">LOADMORE</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<!-- Canvas -->
<div class="canvas">
  <!-- Sidebars -->
  <%= render "layouts/sidebar"%>

  <!-- Content -->
  <div class="content">
    <!-- Header -->
    <%= render partial: "container/header", locals: { title: @store.mall.name }%>
    <!-- Container -->
    <div class="container">
      <div class="shop">
        <!-- Carousel -->
        <div class="carousel" data-plugin="carousel">
          <img src="/images/carousel/carusel01.jpg" alt="carousel" />
          <img src="/images/carousel/carusel02.jpg" alt="carousel" />
          <img src="/images/carousel/carusel03.jpg" alt="carousel" />
          <img src="/images/carousel/carusel04.jpg" alt="carousel" />
          <img src="/images/carousel/carusel05.jpg" alt="carousel" />
          <img src="/images/carousel/carusel06.jpg" alt="carousel" />
        </div>

        <!-- Listing -->
        <div class="listing">
          <div class="item">
            <div class="list">
              <div class="list-image">
                <span class="list-icon small">
                  <i class="spicon spicon-fashion"></i>
                </span>
              </div>
              <div class="list-content align-middle">
                <div class="list-header-text">
                  <div class="timeline-text">
                    <span><%= @store.name %></span>
                  </div>
                  <div class="timeline-text2">
                    <span>Fashion</span>
                  </div>
                </div>
              </div>
              <div class="list-button align-middle" id="spot-button">
                <% if @is_user_following %>
                  <%= render "stores/component/unfollow"%>
                <% else %>
                  <%= render "stores/component/follow"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="shop-tab">
          <div class="menu-title">
            <h3>SHOP</h3>
          </div>
          <div class="menu-link">
            <ul class="tab" role="tablist">
              <li class="active" role="presentation">
                <a href="#shop-index" aria-controls="shop-index" role="tab" data-toggle="tab" data-title="SHOP"><i class="spicon spicon-mall"></i></a>
              </li>
              <li role="presentation">
                <a href="#shop-news" aria-controls="shop-news" role="tab" data-toggle="tab" data-title="NEWS"><i class="spicon spicon-news"></i></a>
              </li>
              <li role="presentation">
                <a href="#shop-detail" aria-controls="shop-detail" role="tab" data-toggle="tab" data-title="DETAILS"><i class="spicon spicon-info"></i></a>
              </li>
              <li role="presentation">
                <a href="http://www.google.co.id/maps" target="_blank"><i class="spicon spicon-map"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane fade in active" id="shop-index">
            <ul class="shop-product">
              <% @products.each do |product| %>
                <li class="item">
                  <%= link_to products_show_malls_path(name:@mall, permalink:@store.permalink, product_id:product) do %>
                    <img src="/images/shop/shop-product-01.jpg" alt="shop product" />
                  <% end %>
                </li>
              <% end %>
            </ul>
            <div class="loadmore">
              <a href="#loadmore">LOADMORE</a>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane fade" id="shop-news">
            <ul class="listing">
              <li class="item">
                <div class="list">
                  <div class="list-content">
                    <h2 class="shop-news-title">Build a Global Company</h2>
                    <div class="shop-news-intro">
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibha.</p>
                    </div>
                  </div>
                  <a href="#" class="list-nav"><i class="spicon spicon-arrow-right"></i></a>
                </div>
              </li>
              <li class="item">
                <div class="list">
                  <div class="list-content">
                    <h2 class="shop-news-title">Maintenance of Our Store</h2>
                    <div class="shop-news-intro">
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibha.</p>
                    </div>
                  </div>
                  <a href="#" class="list-nav"><i class="spicon spicon-arrow-right"></i></a>
                </div>
              </li>
              <li class="item">
                <div class="list">
                  <div class="list-content">
                    <h2 class="shop-news-title">Winter Collection 50% Discount</h2>
                    <div class="shop-news-intro">
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibha.</p>
                    </div>
                  </div>
                  <a href="#" class="list-nav"><i class="spicon spicon-arrow-right"></i></a>
                </div>
              </li>
            </ul>
            <div class="loadmore">
              <a href="#loadmore">LOADMORE</a>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane fade" id="shop-detail">
            <div class="shop-content">
              <h3 class="title">Central Park</h3>
              <p>Unit U15 - Upper Ground Level<br />Jl. Let.Jend. S. Parman Kav.21, Slipi</p>
              <table class="table">
                <tr>
                  <td>Opening Hours</td>
                  <td class="spacer"> : </td>
                  <td>10:00 am – 10:00 pm</td>
                </tr>
                <tr>
                  <td>Phone</td>
                  <td class="spacer"> : </td>
                  <td>021-5609706</td>
                </tr>
              </table>
              <p>Uniqlo Co., Ltd. (株式会社ユニクロ Kabushiki-gaisha yunikuro?) (pronounced "YOU-nee-klo" in English) is a Japanese casual wear designer, manufacturer and retailer. The company has been a wholly owned subsidiary of Fast Retailing Co., Ltd. since November 2005.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :javascript_document do %>
  <%= javascript_include_tag 'libs/jquery/jquery.min' %>
  <%= javascript_include_tag 'libs/bootstrap/transition' %>
  <%= javascript_include_tag 'libs/bootstrap/modal' %>
  <%= javascript_include_tag 'libs/bootstrap/tab' %>
  <%= javascript_include_tag 'libs/plugins/carousel' %>
<% end %>

app/views/stores/unfollow.js.erb
$("#spot-button").html( "<%= escape_javascript(render 'stores/component/follow') %>" );

app/views/stores/user_following.js.erb
$("#store-following-<%= @store.id %>").replaceWith( "<%= escape_javascript(render partial: 'stores/component/user_unfollowing', locals:{following:@store,is_current_user_page:params[:is_current_user_page]}) %>" );

app/views/stores/user_unfollow.js.erb
$("#store-following-<%= @store.id %>").replaceWith( "<%= escape_javascript(render partial: 'stores/component/user_following', locals:{following:@store,is_current_user_page:params[:is_current_user_page]}) %>" );
<% if !params[:is_current_user_page].blank? %>
  $("#store-<%= @store.id %>").remove();
  $("#following-count").html("<%= @following_size %>")
<% end %>