config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :administrators, only: [:index]  do
    get 'users'                       => 'administrators#users',                on: :collection
    get 'malls'                       => 'administrators#malls',                on: :collection
    get 'stores'                      => 'administrators#stores',               on: :collection
    get 'brands'                      => 'administrators#brands',               on: :collection
    get 'products'                    => 'administrators#products',             on: :collection
    get 'promotions'                  => 'administrators#promotions',           on: :collection
    get 'setting'                     => 'administrators#setting',              on: :collection
    get 'import'                      => 'administrators#import',               on: :collection
    # collection { post :import }
  end
  
  resources :malls, only:[:new, :edit, :create, :update] do
    collection { post :import }
  end
  
  resources :malls, only:[] do
    get   ':name/:permalink'                      => 'stores#show',       on: :collection, as: :show
    get   ':name/:permalink/:product_id'          => 'products#show',     on: :collection, as: :products_show
    post  ':name/:permalink/:product_id/reviews'  => 'reviews#create',    on: :collection, as: :reviews_create
    post  ':mall_id/follow'                       => 'malls#follow',      on: :collection, as: :follow
    post  ':mall_id/unfollow'                     => 'malls#unfollow',    on: :collection, as: :unfollow
    resources :stores, only:[:new, :edit, :create, :update]
  end

  resources :brands, only:[:new, :edit, :create, :update] do
    collection { post :import }
    post  ':brand_id/follow'      => 'brands#follow',    on: :collection, as: :follow
    post  ':brand_id/unfollow'    => 'brands#unfollow',  on: :collection, as: :unfollow
  end

  resources :stores, only:[:index] do
    collection { post :import }
    post  ':store_id/follow'      => 'stores#follow',    on: :collection, as: :follow
    post  ':store_id/unfollow'    => 'stores#unfollow',  on: :collection, as: :unfollow
  end

  resources :users, only:[] do
    post  ':user_id/follow'       => 'users#follow',    on: :collection, as: :follow
    post  ':user_id/unfollow'     => 'users#unfollow',  on: :collection, as: :unfollow
  end

  resources :products, only:[] do
    post  ':product_id/like'      => 'products#like',     on: :collection, as: :like
    post  ':product_id/dislike'   => 'products#dislike',  on: :collection, as: :dislike
  end

  resources :reviews, only:[] do
    post  ':review_id/like'      => 'reviews#like',     on: :collection, as: :like
    post  ':review_id/dislike'   => 'reviews#dislike',  on: :collection, as: :dislike
  end

  get   '/:permalink'                 => 'home#profile',                        as: "profile",              :constraints => { :name => /[^\/]+/ }
end

app/views/form/_login.html.erb
<%= form_for(@user, :as => :user, :url => session_path(:user), html: { class: "login-form"}) do |f| %>
  <div class="login-input">
    <%= f.email_field :email, :autofocus => true, placeholder:"Email" %>
  </div>
  <div class="login-input">
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div class="login-button">
    <%= f.submit "LOGIN" %>
  </div>
  <div class="login-link">
    <div class="login-row">
      <div>
        <%= link_to "Forgot", new_password_path(@user) %>
      </div>
      <div>
        <%= link_to "Register", new_registration_path(@user) %>
      </div>
    </div>
  </div>
<% end %>

app/views/form/_mall.html.erb
<%= form_for(@mall, html: { class: "login-form"}) do |f| %>
  <div class="form-group">
    <label for="fullname">NAME</label>
    <%= f.text_field :name, placeholder:"Name" %>
  </div>
  <div class="form-group">
    <label for="fullname">Address</label>
    <%= f.text_field :address, placeholder:"Address" %>
  </div>
  <div class="form-group">
    <label for="fullname">City</label>
    <%= f.text_field :city, placeholder:"City" %>
  </div>
  <div class="form-group">
    <label for="fullname">Lantai</label>
    <%= f.text_field :standing_floor, placeholder:"Lantai" %>
  </div>
  <div class="form-group">
    <label for="fullname">Latitude</label>
    <%= f.text_field :latitude, placeholder:"Latitude" %>
  </div>
  <div class="form-group">
    <label for="fullname">Longitude</label>
    <%= f.text_field :longitude, placeholder:"Longitude" %>
  </div>
  <div class="form-group">
    <button type="submit">SAVE</button>
  </div>
<% end %>

app/views/form/_register.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: "login-form"}) do |f| %>
  <div class="login-input">
    <%= f.text_field :username, placeholder:"Username" %>
  </div>
  <div class="login-input">
    <%= f.text_field :firstname, placeholder:"First Name" %>
  </div>
  <div class="login-input">
    <%= f.text_field :lastname, placeholder:"Last Name" %>
  </div>
  <div class="login-input">
    <%= f.email_field :email, placeholder:"Email" %>
  </div>
  <div class="login-input">
    <%= f.password_field :password, autocomplete: "off",placeholder:"Password" %>
  </div>
  <div class="login-input">
    <%= f.password_field :password_confirmation, autocomplete: "off",placeholder:"Password Confirmation" %>
  </div>
  <div class="login-button">
    <input type="submit" value="REGISTER" />
  </div>
  <div class="login-link">
    <div class="login-row">
      <div>
        <%= link_to "Forgot", new_password_path(resource_name) %>
      </div>
      <div>
        <%= link_to "Login", new_session_path(resource_name) %>
      </div>
    </div>
  </div>
<% end %>

app/views/form/_review.html.erb
<%= form_for @review, url: reviews_create_malls_path(name:@mall, permalink:@store.permalink, product_id:@product), html: { class: "punch-form" } do |f| %>
  <p class="align-center">Punch means you just bought or like this product, so you would like to help to share and recommend it to your friends. Please also rate and tell us why you like this product. Punch!</p>
  <div class="form-rate">
    <div class="label">RATE</div>
    <div class="input" data-action="punch-rate">
      <label class="punch-rate">
        <input type="checkbox" name="score[]" value="1" />
        <i class="spicon spicon-star"></i></label>
      <label class="punch-rate">
        <input type="checkbox" name="score[]" value="2" />
        <i class="spicon spicon-star"></i></label>
      <label class="punch-rate">
        <input type="checkbox" name="score[]" value="3" />
        <i class="spicon spicon-star"></i></label>
      <label class="punch-rate">
        <input type="checkbox" name="score[]" value="4" />
        <i class="spicon spicon-star"></i></label>
      <label class="punch-rate">
        <input type="checkbox" name="score[]" value="5" />
        <i class="spicon spicon-star"></i></label>
    </div>
  </div>
  <%= f.text_area :content, placeholder: "Write something about this product... (max 200 characters)", cols:"30", rows:"4", maxlength:"200" %>
  <div class="punch-form-button">
    <input type="submit" class="button" value="PUNCH" />
  </div>
<% end %>