config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'home#index'

  resources :administrators, only: [:index]  do
    get 'users'                       => 'administrators#users',                on: :collection
    get 'malls'                       => 'administrators#malls',                on: :collection
    get 'stores'                      => 'administrators#stores',               on: :collection
    get 'brands'                      => 'administrators#brands',               on: :collection
    get 'products'                    => 'administrators#products',             on: :collection
    get 'promotions'                  => 'administrators#promotions',           on: :collection
    get 'setting'                     => 'administrators#setting',              on: :collection
    get 'import'                      => 'administrators#import',               on: :collection
    # collection { post :import }
  end
  
  resources :malls, only:[:new, :edit, :create, :update] do
    collection { post :import }
  end
  
  resources :malls, only:[] do
    get   ':name/:permalink'                      => 'stores#show',       on: :collection, as: :show
    get   ':name/:permalink/:product_id'          => 'products#show',     on: :collection, as: :products_show
    post  ':name/:permalink/:product_id/reviews'  => 'reviews#create',    on: :collection, as: :reviews_create
    post  ':mall_id/follow'                       => 'malls#follow',      on: :collection, as: :follow
    post  ':mall_id/unfollow'                     => 'malls#unfollow',    on: :collection, as: :unfollow
    resources :stores, only:[:new, :edit, :create, :update]
  end

  resources :brands, only:[:new, :edit, :create, :update] do
    collection { post :import }
    post  ':brand_id/follow'      => 'brands#follow',    on: :collection, as: :follow
    post  ':brand_id/unfollow'    => 'brands#unfollow',  on: :collection, as: :unfollow
  end

  resources :stores, only:[:index] do
    collection { post :import }
    post  ':store_id/follow'      => 'stores#follow',    on: :collection, as: :follow
    post  ':store_id/unfollow'    => 'stores#unfollow',  on: :collection, as: :unfollow
  end

  resources :users, only:[] do
    post  ':user_id/follow'       => 'users#follow',    on: :collection, as: :follow
    post  ':user_id/unfollow'     => 'users#unfollow',  on: :collection, as: :unfollow
  end

  resources :products, only:[] do
    post  ':product_id/like'      => 'products#like',     on: :collection, as: :like
    post  ':product_id/dislike'   => 'products#dislike',  on: :collection, as: :dislike
  end

  resources :reviews, only:[] do
    post  ':review_id/like'      => 'reviews#like',     on: :collection, as: :like
    post  ':review_id/dislike'   => 'reviews#dislike',  on: :collection, as: :dislike
  end

  get   '/:permalink'                 => 'home#profile',                        as: "profile",              :constraints => { :name => /[^\/]+/ }
end

app/views/container/_header.html.erb
<header class="navbar">
  <div class="navbar-inner">
    <!-- Left Icon -->
    <a id="toogle-sidebar" href="#" class="visible-phone pull-left">
      <i class="spicon spicon-nav"></i>
    </a>

    <!-- Right Icon -->
    <a href="#" data-toggle="modal" data-target="#spotpunch-modal" class="pull-right">
      <i class="spicon spicon-search"></i>
    </a>

    <!-- Header Title -->
    <h1 class="navbar-title"><%= title %></h1>
  </div>
</header>

app/views/container/_official_shop.html.erb
<li class="item">
  <div class="list">
    <div class="list-image">
      <a href="shop.html" class="list-logo">
        <img src="images/logo/logo01.jpg" alt="logo" />
      </a>
    </div>
    <div class="list-content">
      <div class="list-header">
        <div class="header-text">
          <div class="text1">
            <%= link_to shop.name, show_malls_path(name:shop.mall.permalink, permalink:shop.permalink) %>
          </div>
          <div class="text2">
            <a href="shop.html#shop-news">Midnight Sale</a>
          </div>
        </div>
        <a class="list-nav" href="shop.html#shop-news"><i class="spicon spicon-arrow-right"></i></a>
      </div>
      <div class="list-body">
        <p>Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
      </div>
    </div>
  </div>
</li>

app/views/container/_profile.html.erb
<div class="sidebar-profile">
  <%= link_to profile_path(permalink:current_user.username) do %>
    <% if current_user.image.blank? %>
      <img class="sidebar-profile-image" src="/images/photo/photo01.jpg" alt="profile" />
    <% else %>
      <img class="sidebar-profile-image" src="<%= current_user.image.avatar.thumb.url %>" alt="profile" />
    <% end %>
  <% end %>
  <div class="sidebar-profile-body">
    <div class="sidebar-profile-name"><%= display_name current_user %></div>
    <%= link_to "Edit Profile", edit_user_registration_path %>
  </div>
</div>

app/views/container/_shop.html.erb
<li class="item">
  <div class="list">
    <div class="list-image">
      <%= link_to profile_path(permalink:current_user.username), class: "list-photo" do %>
          <img src="images/photo/photo02.jpg" alt="photo" />
          <span class="verify-icon"><i class="spicon spicon-check"></i></span>
      <% end %>
    </div>
    <div class="list-content">
      <div class="list-header">
        <div class="list-header-text">
          <div class="timeline-text1">
            <%= link_to shop.name, show_malls_path(name:shop.mall.id, permalink:shop.id) %>
          </div>
          <div class="timeline-text2">
            <a href="#">Macbook Pro Retina Display</a>
          </div>
          <div class="timeline-text3">
            <a href="#">Lotte Shopping Avenue</a>
          </div>
        </div>
        <div class="list-nav list-flip">
          <div class="flip-container">
            <div class="flipper">
              <div class="front">
                <img src="images/product/product02.jpg" alt="product" />
              </div>
              <div class="back">
                <div class="list-action">
                  <a href="#"><i class="spicon spicon-like"></i></a>
                  <a href="#"><i class="spicon spicon-comment"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="list-comment spicon spicon-quote">
    <h4><a href="profile.html">Takeshi Kaneshiro</a></h4>
    <p>このラップトップは本当に素晴らしいです、私はもうそれなしでは生きすることを想像することはできません</p>
  </div>
</li>